# Load Unix socket input (creates /dev/log)
module(load="imuxsock")

# Basic logging format
template(name="SimpleFormat" type="string"
         string="%timegenerated% %syslogtag%%msg%\n")

# Log everything to /var/log/messages
*.* /var/log/messages;SimpleFormat

# Additionally, send log messages to /dev/stdout, which podman logs can read from
*.* /dev/stdout;SimpleFormat
